Create 关于jprotobuf在安卓工程上运行异常
安卓上无法调用java编译器进行编译，不知道大神有没发现这问题，不知道还能不能解决这问题，希望尽快~
您好：请看描述
在android项目上调用ProtobufProxy.create(xxx)总是报Caused by: java.lang.NoClassDefFoundError:javax.tools.ToolProvider
异常最终定位行数为   JdkCompiler类的：private final JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();